# Generated by Django 2.0.6 on 2021-08-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('pk_examen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('bimestre', models.CharField(max_length=50)),
                ('punteo', models.CharField(max_length=100, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
    ]
